name: Build rustdoc
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
      with:
        repository: hkmatsumoto/rust
        ref: roogle
        path: rust
        fetch-depth: 50
    - name: Set `config.toml`
      working-directory: rust
      shell: bash
      run: |
        patch < ../config.toml.patch
        mv config.toml.example config.toml
    - name: Build rustdoc
      working-directory: rust
      shell: bash
      run: ./x.py build src/librustdoc
