name: Indexer

on:
  schedule:
    - cron: '* 0 * * SUN'

jobs:
  libstd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - uses: ./.github/actions/build-rustc/
      - uses: actions-rs/cargo@v1
        with:
          command: install
          args: --path indexer
      - name: Index libstd crates
        run: indexer-libstd
        working-directory: rust
      - run: |
          rm -rf rust
          git pull origin ${{ github.ref }}
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "libstd: Weekly update"
          commit_user_name: "Melchior 1"
          commit_user_email: "github-actions[bot]@users.noreply.github.com"
          commit_author: "Melchior 1 <melchior@exmaple.com>"
  rustc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - uses: ./.github/actions/build-rustc/
      - uses: actions-rs/cargo@v1
        with:
          command: install
          args: --path indexer
      - name: Index rustc crates
        run: indexer-rustc
        working-directory: rust
      - run: |
          rm -rf rust
          git pull origin ${{ github.ref }}
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "rustc: Weekly update"
          commit_user_name: "Balthasar 2"
          commit_user_email: "github-actions[bot]@users.noreply.github.com"
          commit_author: "Balthasar 2 <balthasar@exmaple.com>"
